# Generated by Django 3.1.5 on 2021-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210104_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_day',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='date_month',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='date_year',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_with_credit_card',
            field=models.BooleanField(default=False),
        ),
    ]
