# Generated by Django 3.1.5 on 2021-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210124_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date_day',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='date_month',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='date_year',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
