# Generated by Django 3.1.5 on 2021-02-26 20:03

from django.db import migrations


def migrate_expenses(apps, schema_editor):
    Expense = apps.get_model('core', 'Expense')
    for expense in Expense.objects.all():
        if not expense.date_year or not expense.date_month or not expense.date_day:
            expense.date_year = expense.date.year
            expense.date_month = expense.date.month
            expense.date_day = expense.date.day
            expense.save()
            print(f"Migrated expense {expense.pk}")


def migrate_income(apps, schema_editor):
    Income = apps.get_model('core', 'Income')
    for income in Income.objects.all():
        if not income.date_year or not income.date_month or not income.date_day:
            income.date_year = income.date.year
            income.date_month = income.date.month
            income.date_day = income.date.day
            income.save()
            print(f"Migrated income {income.pk}")


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20210226_1959'),
    ]

    operations = [
        migrations.RunPython(migrate_expenses, migrations.RunPython.noop),
        migrations.RunPython(migrate_income, migrations.RunPython.noop)
    ]
